/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Estado.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Estado.pb-c.h"
void   bftbench__estado__init
                     (Bftbench__Estado         *message)
{
  static Bftbench__Estado init_value = BFTBENCH__ESTADO__INIT;
  *message = init_value;
}
size_t bftbench__estado__get_packed_size
                     (const Bftbench__Estado *message)
{
  assert(message->base.descriptor == &bftbench__estado__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bftbench__estado__pack
                     (const Bftbench__Estado *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bftbench__estado__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bftbench__estado__pack_to_buffer
                     (const Bftbench__Estado *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bftbench__estado__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bftbench__Estado *
       bftbench__estado__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bftbench__Estado *)
     protobuf_c_message_unpack (&bftbench__estado__descriptor,
                                allocator, len, data);
}
void   bftbench__estado__free_unpacked
                     (Bftbench__Estado *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &bftbench__estado__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor bftbench__estado__field_descriptors[1] =
{
  {
    "lista",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Bftbench__Estado, n_lista),
    offsetof(Bftbench__Estado, lista),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bftbench__estado__field_indices_by_name[] = {
  0,   /* field[0] = lista */
};
static const ProtobufCIntRange bftbench__estado__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor bftbench__estado__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bftbench.Estado",
  "Estado",
  "Bftbench__Estado",
  "bftbench",
  sizeof(Bftbench__Estado),
  1,
  bftbench__estado__field_descriptors,
  bftbench__estado__field_indices_by_name,
  1,  bftbench__estado__number_ranges,
  (ProtobufCMessageInit) bftbench__estado__init,
  NULL,NULL,NULL    /* reserved[123] */
};
