/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Request.pb-c.h"
void   bftbench__request__init
                     (Bftbench__Request         *message)
{
  static Bftbench__Request init_value = BFTBENCH__REQUEST__INIT;
  *message = init_value;
}
size_t bftbench__request__get_packed_size
                     (const Bftbench__Request *message)
{
  assert(message->base.descriptor == &bftbench__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bftbench__request__pack
                     (const Bftbench__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bftbench__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bftbench__request__pack_to_buffer
                     (const Bftbench__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bftbench__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bftbench__Request *
       bftbench__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bftbench__Request *)
     protobuf_c_message_unpack (&bftbench__request__descriptor,
                                allocator, len, data);
}
void   bftbench__request__free_unpacked
                     (Bftbench__Request *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &bftbench__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue bftbench__request__request_type__enum_values_by_number[5] =
{
  { "ADD", "BFTBENCH__REQUEST__REQUEST_TYPE__ADD", 0 },
  { "REMOVE", "BFTBENCH__REQUEST__REQUEST_TYPE__REMOVE", 1 },
  { "SIZE", "BFTBENCH__REQUEST__REQUEST_TYPE__SIZE", 2 },
  { "CONTAINS", "BFTBENCH__REQUEST__REQUEST_TYPE__CONTAINS", 3 },
  { "GET", "BFTBENCH__REQUEST__REQUEST_TYPE__GET", 4 },
};
static const ProtobufCIntRange bftbench__request__request_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex bftbench__request__request_type__enum_values_by_name[5] =
{
  { "ADD", 0 },
  { "CONTAINS", 3 },
  { "GET", 4 },
  { "REMOVE", 1 },
  { "SIZE", 2 },
};
const ProtobufCEnumDescriptor bftbench__request__request_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "bftbench.Request.RequestType",
  "RequestType",
  "Bftbench__Request__RequestType",
  "bftbench",
  5,
  bftbench__request__request_type__enum_values_by_number,
  5,
  bftbench__request__request_type__enum_values_by_name,
  1,
  bftbench__request__request_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor bftbench__request__field_descriptors[2] =
{
  {
    "action",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Bftbench__Request, action),
    &bftbench__request__request_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Bftbench__Request, has_value),
    offsetof(Bftbench__Request, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bftbench__request__field_indices_by_name[] = {
  0,   /* field[0] = action */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange bftbench__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor bftbench__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bftbench.Request",
  "Request",
  "Bftbench__Request",
  "bftbench",
  sizeof(Bftbench__Request),
  2,
  bftbench__request__field_descriptors,
  bftbench__request__field_indices_by_name,
  1,  bftbench__request__number_ranges,
  (ProtobufCMessageInit) bftbench__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
