/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Response.proto */

#ifndef PROTOBUF_C_Response_2eproto__INCLUDED
#define PROTOBUF_C_Response_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Bftbench__Response Bftbench__Response;


/* --- enums --- */


/* --- messages --- */

struct  _Bftbench__Response
{
  ProtobufCMessage base;
  protobuf_c_boolean has_boolresponse;
  protobuf_c_boolean boolresponse;
  protobuf_c_boolean has_intresponse;
  int32_t intresponse;
};
#define BFTBENCH__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bftbench__response__descriptor) \
    , 0,0, 0,0 }


/* Bftbench__Response methods */
void   bftbench__response__init
                     (Bftbench__Response         *message);
size_t bftbench__response__get_packed_size
                     (const Bftbench__Response   *message);
size_t bftbench__response__pack
                     (const Bftbench__Response   *message,
                      uint8_t             *out);
size_t bftbench__response__pack_to_buffer
                     (const Bftbench__Response   *message,
                      ProtobufCBuffer     *buffer);
Bftbench__Response *
       bftbench__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bftbench__response__free_unpacked
                     (Bftbench__Response *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Bftbench__Response_Closure)
                 (const Bftbench__Response *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor bftbench__response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Response_2eproto__INCLUDED */
