/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: testcount.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "testcount.pb-c.h"
void   counter__init
                     (Counter         *message)
{
  static Counter init_value = COUNTER__INIT;
  *message = init_value;
}
size_t counter__get_packed_size
                     (const Counter *message)
{
  assert(message->base.descriptor == &counter__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t counter__pack
                     (const Counter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &counter__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t counter__pack_to_buffer
                     (const Counter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &counter__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Counter *
       counter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Counter *)
     protobuf_c_message_unpack (&counter__descriptor,
                                allocator, len, data);
}
void   counter__free_unpacked
                     (Counter *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &counter__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor counter__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Counter, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned counter__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange counter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor counter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Counter",
  "Counter",
  "Counter",
  "",
  sizeof(Counter),
  1,
  counter__field_descriptors,
  counter__field_indices_by_name,
  1,  counter__number_ranges,
  (ProtobufCMessageInit) counter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
