all :
	cd protobuf; make
	cd python; make
	cd c; make
	cd cpp; make
	cd java; make


clean :
	cd protobuf; make clean
	cd python; make clean
	cd c; make clean
	cd cpp; make clean
	cd java; make clean
