all:
	cd zero; make
	cd zero_plain; make
	cd list2; make
	cd list; make
	cd kv; make
	cd array; make

.PHONY: clean

clean:
	cd zero; make clean
	cd zero_plain; make
	cd list2; make clean
	cd list; make clean
	cd kv; make clean
	cd array; make clean


   


