// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Estado.proto

#ifndef PROTOBUF_Estado_2eproto__INCLUDED
#define PROTOBUF_Estado_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace bftbench {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Estado_2eproto();
void protobuf_AssignDesc_Estado_2eproto();
void protobuf_ShutdownFile_Estado_2eproto();

class Estado;

// ===================================================================

class Estado : public ::google::protobuf::Message {
 public:
  Estado();
  virtual ~Estado();

  Estado(const Estado& from);

  inline Estado& operator=(const Estado& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Estado& default_instance();

  void Swap(Estado* other);

  // implements Message ----------------------------------------------

  Estado* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Estado& from);
  void MergeFrom(const Estado& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 lista = 1;
  inline int lista_size() const;
  inline void clear_lista();
  static const int kListaFieldNumber = 1;
  inline ::google::protobuf::int32 lista(int index) const;
  inline void set_lista(int index, ::google::protobuf::int32 value);
  inline void add_lista(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      lista() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_lista();

  // @@protoc_insertion_point(class_scope:bftbench.Estado)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > lista_;
  friend void  protobuf_AddDesc_Estado_2eproto();
  friend void protobuf_AssignDesc_Estado_2eproto();
  friend void protobuf_ShutdownFile_Estado_2eproto();

  void InitAsDefaultInstance();
  static Estado* default_instance_;
};
// ===================================================================


// ===================================================================

// Estado

// repeated int32 lista = 1;
inline int Estado::lista_size() const {
  return lista_.size();
}
inline void Estado::clear_lista() {
  lista_.Clear();
}
inline ::google::protobuf::int32 Estado::lista(int index) const {
  // @@protoc_insertion_point(field_get:bftbench.Estado.lista)
  return lista_.Get(index);
}
inline void Estado::set_lista(int index, ::google::protobuf::int32 value) {
  lista_.Set(index, value);
  // @@protoc_insertion_point(field_set:bftbench.Estado.lista)
}
inline void Estado::add_lista(::google::protobuf::int32 value) {
  lista_.Add(value);
  // @@protoc_insertion_point(field_add:bftbench.Estado.lista)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Estado::lista() const {
  // @@protoc_insertion_point(field_list:bftbench.Estado.lista)
  return lista_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Estado::mutable_lista() {
  // @@protoc_insertion_point(field_mutable_list:bftbench.Estado.lista)
  return &lista_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace bftbench

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Estado_2eproto__INCLUDED
