// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

#ifndef PROTOBUF_Request_2eproto__INCLUDED
#define PROTOBUF_Request_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace bftbench {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Request_2eproto();
void protobuf_AssignDesc_Request_2eproto();
void protobuf_ShutdownFile_Request_2eproto();

class Request;

enum Request_RequestType {
  Request_RequestType_ADD = 0,
  Request_RequestType_REMOVE = 1,
  Request_RequestType_SIZE = 2,
  Request_RequestType_CONTAINS = 3,
  Request_RequestType_GET = 4
};
bool Request_RequestType_IsValid(int value);
const Request_RequestType Request_RequestType_RequestType_MIN = Request_RequestType_ADD;
const Request_RequestType Request_RequestType_RequestType_MAX = Request_RequestType_GET;
const int Request_RequestType_RequestType_ARRAYSIZE = Request_RequestType_RequestType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Request_RequestType_descriptor();
inline const ::std::string& Request_RequestType_Name(Request_RequestType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Request_RequestType_descriptor(), value);
}
inline bool Request_RequestType_Parse(
    const ::std::string& name, Request_RequestType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Request_RequestType>(
    Request_RequestType_descriptor(), name, value);
}
// ===================================================================

class Request : public ::google::protobuf::Message {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  void Swap(Request* other);

  // implements Message ----------------------------------------------

  Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Request_RequestType RequestType;
  static const RequestType ADD = Request_RequestType_ADD;
  static const RequestType REMOVE = Request_RequestType_REMOVE;
  static const RequestType SIZE = Request_RequestType_SIZE;
  static const RequestType CONTAINS = Request_RequestType_CONTAINS;
  static const RequestType GET = Request_RequestType_GET;
  static inline bool RequestType_IsValid(int value) {
    return Request_RequestType_IsValid(value);
  }
  static const RequestType RequestType_MIN =
    Request_RequestType_RequestType_MIN;
  static const RequestType RequestType_MAX =
    Request_RequestType_RequestType_MAX;
  static const int RequestType_ARRAYSIZE =
    Request_RequestType_RequestType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RequestType_descriptor() {
    return Request_RequestType_descriptor();
  }
  static inline const ::std::string& RequestType_Name(RequestType value) {
    return Request_RequestType_Name(value);
  }
  static inline bool RequestType_Parse(const ::std::string& name,
      RequestType* value) {
    return Request_RequestType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .bftbench.Request.RequestType action = 1;
  inline bool has_action() const;
  inline void clear_action();
  static const int kActionFieldNumber = 1;
  inline ::bftbench::Request_RequestType action() const;
  inline void set_action(::bftbench::Request_RequestType value);

  // optional int32 value = 2;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline ::google::protobuf::int32 value() const;
  inline void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:bftbench.Request)
 private:
  inline void set_has_action();
  inline void clear_has_action();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int action_;
  ::google::protobuf::int32 value_;
  friend void  protobuf_AddDesc_Request_2eproto();
  friend void protobuf_AssignDesc_Request_2eproto();
  friend void protobuf_ShutdownFile_Request_2eproto();

  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// ===================================================================


// ===================================================================

// Request

// required .bftbench.Request.RequestType action = 1;
inline bool Request::has_action() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_action() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_action() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_action() {
  action_ = 0;
  clear_has_action();
}
inline ::bftbench::Request_RequestType Request::action() const {
  // @@protoc_insertion_point(field_get:bftbench.Request.action)
  return static_cast< ::bftbench::Request_RequestType >(action_);
}
inline void Request::set_action(::bftbench::Request_RequestType value) {
  assert(::bftbench::Request_RequestType_IsValid(value));
  set_has_action();
  action_ = value;
  // @@protoc_insertion_point(field_set:bftbench.Request.action)
}

// optional int32 value = 2;
inline bool Request::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline ::google::protobuf::int32 Request::value() const {
  // @@protoc_insertion_point(field_get:bftbench.Request.value)
  return value_;
}
inline void Request::set_value(::google::protobuf::int32 value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:bftbench.Request.value)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace bftbench

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::bftbench::Request_RequestType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bftbench::Request_RequestType>() {
  return ::bftbench::Request_RequestType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Request_2eproto__INCLUDED
