/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bftsmart_tom_diversity_ServerWrapper */

#ifndef _Included_bftsmart_tom_diversity_ServerWrapper
#define _Included_bftsmart_tom_diversity_ServerWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bftsmart_tom_diversity_ServerWrapper
 * Method:    executeOrderedNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_bftsmart_tom_diversity_ServerWrapper_executeOrderedNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     bftsmart_tom_diversity_ServerWrapper
 * Method:    executeUnorderedNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_bftsmart_tom_diversity_ServerWrapper_executeUnorderedNative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     bftsmart_tom_diversity_ServerWrapper
 * Method:    getSnapshotNative
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_bftsmart_tom_diversity_ServerWrapper_getSnapshotNative
  (JNIEnv *, jobject);

/*
 * Class:     bftsmart_tom_diversity_ServerWrapper
 * Method:    installSnapshotNative
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_bftsmart_tom_diversity_ServerWrapper_installSnapshotNative
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
