// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

#ifndef PROTOBUF_Response_2eproto__INCLUDED
#define PROTOBUF_Response_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace bftbench {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Response_2eproto();
void protobuf_AssignDesc_Response_2eproto();
void protobuf_ShutdownFile_Response_2eproto();

class Response;

// ===================================================================

class Response : public ::google::protobuf::Message {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  void Swap(Response* other);

  // implements Message ----------------------------------------------

  Response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool BoolResponse = 1;
  inline bool has_boolresponse() const;
  inline void clear_boolresponse();
  static const int kBoolResponseFieldNumber = 1;
  inline bool boolresponse() const;
  inline void set_boolresponse(bool value);

  // optional int32 IntResponse = 2;
  inline bool has_intresponse() const;
  inline void clear_intresponse();
  static const int kIntResponseFieldNumber = 2;
  inline ::google::protobuf::int32 intresponse() const;
  inline void set_intresponse(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:bftbench.Response)
 private:
  inline void set_has_boolresponse();
  inline void clear_has_boolresponse();
  inline void set_has_intresponse();
  inline void clear_has_intresponse();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool boolresponse_;
  ::google::protobuf::int32 intresponse_;
  friend void  protobuf_AddDesc_Response_2eproto();
  friend void protobuf_AssignDesc_Response_2eproto();
  friend void protobuf_ShutdownFile_Response_2eproto();

  void InitAsDefaultInstance();
  static Response* default_instance_;
};
// ===================================================================


// ===================================================================

// Response

// optional bool BoolResponse = 1;
inline bool Response::has_boolresponse() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_boolresponse() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_boolresponse() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_boolresponse() {
  boolresponse_ = false;
  clear_has_boolresponse();
}
inline bool Response::boolresponse() const {
  // @@protoc_insertion_point(field_get:bftbench.Response.BoolResponse)
  return boolresponse_;
}
inline void Response::set_boolresponse(bool value) {
  set_has_boolresponse();
  boolresponse_ = value;
  // @@protoc_insertion_point(field_set:bftbench.Response.BoolResponse)
}

// optional int32 IntResponse = 2;
inline bool Response::has_intresponse() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_intresponse() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_intresponse() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_intresponse() {
  intresponse_ = 0;
  clear_has_intresponse();
}
inline ::google::protobuf::int32 Response::intresponse() const {
  // @@protoc_insertion_point(field_get:bftbench.Response.IntResponse)
  return intresponse_;
}
inline void Response::set_intresponse(::google::protobuf::int32 value) {
  set_has_intresponse();
  intresponse_ = value;
  // @@protoc_insertion_point(field_set:bftbench.Response.IntResponse)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace bftbench

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Response_2eproto__INCLUDED
