# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testcount.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='testcount.proto',
  package='testebft',
  serialized_pb=_b('\n\x0ftestcount.proto\x12\x08testebft\"\x18\n\x07\x43ounter\x12\r\n\x05value\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COUNTER = _descriptor.Descriptor(
  name='Counter',
  full_name='testebft.Counter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='testebft.Counter.value', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['Counter'] = _COUNTER

Counter = _reflection.GeneratedProtocolMessageType('Counter', (_message.Message,), dict(
  DESCRIPTOR = _COUNTER,
  __module__ = 'testcount_pb2'
  # @@protoc_insertion_point(class_scope:testebft.Counter)
  ))
_sym_db.RegisterMessage(Counter)


# @@protoc_insertion_point(module_scope)
