# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Vazio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Vazio.proto',
  package='bftbench',
  serialized_pb=_b('\n\x0bVazio.proto\x12\x08\x62\x66tbench\"\x07\n\x05Vazio')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VAZIO = _descriptor.Descriptor(
  name='Vazio',
  full_name='bftbench.Vazio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=32,
)

DESCRIPTOR.message_types_by_name['Vazio'] = _VAZIO

Vazio = _reflection.GeneratedProtocolMessageType('Vazio', (_message.Message,), dict(
  DESCRIPTOR = _VAZIO,
  __module__ = 'Vazio_pb2'
  # @@protoc_insertion_point(class_scope:bftbench.Vazio)
  ))
_sym_db.RegisterMessage(Vazio)


# @@protoc_insertion_point(module_scope)
