/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Response.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Response.pb-c.h"
void   bftbench__response__init
                     (Bftbench__Response         *message)
{
  static Bftbench__Response init_value = BFTBENCH__RESPONSE__INIT;
  *message = init_value;
}
size_t bftbench__response__get_packed_size
                     (const Bftbench__Response *message)
{
  assert(message->base.descriptor == &bftbench__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bftbench__response__pack
                     (const Bftbench__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bftbench__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bftbench__response__pack_to_buffer
                     (const Bftbench__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bftbench__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bftbench__Response *
       bftbench__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bftbench__Response *)
     protobuf_c_message_unpack (&bftbench__response__descriptor,
                                allocator, len, data);
}
void   bftbench__response__free_unpacked
                     (Bftbench__Response *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &bftbench__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor bftbench__response__field_descriptors[2] =
{
  {
    "BoolResponse",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Bftbench__Response, has_boolresponse),
    offsetof(Bftbench__Response, boolresponse),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "IntResponse",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Bftbench__Response, has_intresponse),
    offsetof(Bftbench__Response, intresponse),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bftbench__response__field_indices_by_name[] = {
  0,   /* field[0] = BoolResponse */
  1,   /* field[1] = IntResponse */
};
static const ProtobufCIntRange bftbench__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor bftbench__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bftbench.Response",
  "Response",
  "Bftbench__Response",
  "bftbench",
  sizeof(Bftbench__Response),
  2,
  bftbench__response__field_descriptors,
  bftbench__response__field_indices_by_name,
  1,  bftbench__response__number_ranges,
  (ProtobufCMessageInit) bftbench__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
