/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: testcount.proto */

#ifndef PROTOBUF_C_testcount_2eproto__INCLUDED
#define PROTOBUF_C_testcount_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Counter Counter;


/* --- enums --- */


/* --- messages --- */

struct  _Counter
{
  ProtobufCMessage base;
  int32_t value;
};
#define COUNTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&counter__descriptor) \
    , 0 }


/* Counter methods */
void   counter__init
                     (Counter         *message);
size_t counter__get_packed_size
                     (const Counter   *message);
size_t counter__pack
                     (const Counter   *message,
                      uint8_t             *out);
size_t counter__pack_to_buffer
                     (const Counter   *message,
                      ProtobufCBuffer     *buffer);
Counter *
       counter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   counter__free_unpacked
                     (Counter *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Counter_Closure)
                 (const Counter *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor counter__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_testcount_2eproto__INCLUDED */
