/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Estado.proto */

#ifndef PROTOBUF_C_Estado_2eproto__INCLUDED
#define PROTOBUF_C_Estado_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Bftbench__Estado Bftbench__Estado;


/* --- enums --- */


/* --- messages --- */

struct  _Bftbench__Estado
{
  ProtobufCMessage base;
  size_t n_lista;
  int32_t *lista;
};
#define BFTBENCH__ESTADO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bftbench__estado__descriptor) \
    , 0,NULL }


/* Bftbench__Estado methods */
void   bftbench__estado__init
                     (Bftbench__Estado         *message);
size_t bftbench__estado__get_packed_size
                     (const Bftbench__Estado   *message);
size_t bftbench__estado__pack
                     (const Bftbench__Estado   *message,
                      uint8_t             *out);
size_t bftbench__estado__pack_to_buffer
                     (const Bftbench__Estado   *message,
                      ProtobufCBuffer     *buffer);
Bftbench__Estado *
       bftbench__estado__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bftbench__estado__free_unpacked
                     (Bftbench__Estado *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Bftbench__Estado_Closure)
                 (const Bftbench__Estado *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor bftbench__estado__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Estado_2eproto__INCLUDED */
